# Generated by Django 4.1.4 on 2022-12-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_schedule_course_edition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='course_edition_id',
            field=models.CharField(max_length=24),
        ),
    ]
