# Generated by Django 4.1.4 on 2022-12-15 02:38

import django.core.validators
from django.db import migrations, models
import django_prometheus.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_id', models.UUIDField(default=uuid.uuid4)),
                ('student_id', models.PositiveBigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('deadline', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('tuitionfee'), models.Model),
        ),
    ]
