# Generated by Django 4.1.4 on 2022-12-16 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
